// Secure email template functions to prevent XSS
export const escapeHtml = (text: string): string => {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
};

export const createAdminEmailTemplate = (name: string, phone: string, email: string, color: string): string => {
  const safeName = escapeHtml(name);
  const safePhone = escapeHtml(phone);
  const safeEmail = escapeHtml(email);
  const safeColor = escapeHtml(color);
  
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Stock Notification Request</title></head><body style="font-family: Arial, sans-serif; background-color: #f8fafc; margin: 0; padding: 20px;"><div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);"><div style="background: linear-gradient(135deg, #1f2937 0%, #374151 100%); padding: 30px; text-align: center; border-radius: 12px 12px 0 0;"><h1 style="color: #ffffff; font-size: 24px; font-weight: 600; margin: 0;">Stock Notification Request</h1><p style="color: #d1d5db; margin: 10px 0 0 0;">Ximpul Flow - Customer Alert</p></div><div style="padding: 30px;"><div style="background-color: #f0f9ff; border-left: 4px solid #3b82f6; padding: 20px; margin-bottom: 25px; border-radius: 6px;"><h3 style="color: #1e40af; margin: 0 0 10px 0; font-size: 16px;">Customer Information</h3><table style="width: 100%; border-collapse: collapse;"><tr><td style="padding: 8px 0; color: #374151; font-weight: 500;">Name:</td><td style="padding: 8px 0; color: #1f2937; font-weight: 600;">${safeName}</td></tr><tr><td style="padding: 8px 0; color: #374151; font-weight: 500;">Phone:</td><td style="padding: 8px 0; color: #1f2937; font-weight: 600;">${safePhone}</td></tr><tr><td style="padding: 8px 0; color: #374151; font-weight: 500;">Email:</td><td style="padding: 8px 0; color: #1f2937; font-weight: 600;">${safeEmail}</td></tr></table></div><div style="background-color: #fef3c7; border-left: 4px solid #f59e0b; padding: 20px; margin-bottom: 25px; border-radius: 6px;"><h3 style="color: #d97706; margin: 0 0 10px 0; font-size: 16px;">Product Request</h3><p style="color: #92400e; margin: 0; font-size: 16px; font-weight: 600;">Ximpul Flow - ${safeColor}</p></div><div style="background-color: #f0fdf4; border-left: 4px solid #10b981; padding: 20px; border-radius: 6px;"><h3 style="color: #047857; margin: 0 0 10px 0; font-size: 16px;">Action Required</h3><p style="color: #065f46; margin: 0; line-height: 1.6;">Please notify this customer when <strong>${safeColor}</strong> is back in stock. Customer is waiting for availability confirmation.</p></div></div><div style="background-color: #f9fafb; padding: 20px; text-align: center; border-radius: 0 0 12px 12px; border-top: 1px solid #e5e7eb;"><p style="color: #6b7280; font-size: 12px; margin: 0;">Ximpul Admin Panel | Stock Management System</p><p style="color: #9ca3af; font-size: 11px; margin: 5px 0 0 0;">This is an automated notification</p></div></div></body></html>`;
};

export const createCustomerEmailTemplate = (name: string, color: string): string => {
  const safeName = escapeHtml(name);
  const safeColor = escapeHtml(color);
  
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Stock Alert Confirmation</title></head><body style="font-family: Arial, sans-serif; background-color: #f8fafc; margin: 0; padding: 20px;"><div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);"><div style="background: linear-gradient(135deg, #1f2937 0%, #111827 100%); padding: 40px 30px; text-align: center; border-radius: 12px 12px 0 0;"><h1 style="color: #ffffff; font-size: 28px; font-weight: 300; margin: 0 0 10px 0; letter-spacing: 1px;">XIMPUL FLOW</h1><p style="color: #d1d5db; font-size: 16px; margin: 0;">Stock Alert Registered</p></div><div style="padding: 40px 30px; text-align: center;"><div style="width: 60px; height: 60px; background-color: #10b981; border-radius: 50%; margin: 0 auto 20px; display: flex; align-items: center; justify-content: center;"><span style="color: white; font-size: 24px;">✓</span></div><h2 style="color: #1f2937; font-size: 24px; font-weight: 400; margin: 0 0 10px 0;">Thank You, ${safeName}!</h2><p style="color: #6b7280; font-size: 16px; margin: 0 0 30px 0;">We've registered your interest for <strong>${safeColor}</strong></p><div style="background-color: #f0fdf4; border-left: 4px solid #10b981; padding: 20px; margin-bottom: 30px; text-align: left;"><h4 style="color: #065f46; font-size: 16px; font-weight: 600; margin: 0 0 10px 0;">What happens next?</h4><p style="color: #047857; margin: 0; line-height: 1.6;">We'll notify you as soon as ${safeColor} is back in stock. You'll receive an email and SMS notification when it's available for purchase.</p></div><div style="text-align: center; padding: 20px 0;"><p style="color: #6b7280; font-size: 16px; line-height: 1.6; margin: 0 0 15px 0;">Thank you for choosing Ximpul Flow - a product built with care, purpose, and the belief that water should be free.</p><p style="color: #1f2937; font-weight: 600; font-size: 18px; margin: 0;">Your Water. Your Freedom.</p></div></div><div style="background-color: #f9fafb; padding: 30px; text-align: center; border-top: 1px solid #e5e7eb; border-radius: 0 0 12px 12px;"><p style="color: #6b7280; font-size: 14px; margin: 0 0 10px 0;">Need help? Contact us:</p><p style="color: #1f2937; font-weight: 600; margin: 0;">Email: ximpulshop@gmail.com | Phone: 01881408611</p><p style="color: #9ca3af; font-size: 12px; margin: 15px 0 0 0;">Copyright 2024 Ximpul. All rights reserved.</p></div></div></body></html>`;
};